### ISSUE TITLE
latest gcloud components update (0.9.50) breaks gcloud on centos-6

### ISSUE THREAD

**Issue by spacepod** [GoogleCloudPlatform/gcloud#21]
```
natalie@local $ gcloud compute instances create centos-6-test-`date +%Y-%m-%d-%H-%M-%S` --image centos-6
Created [https://www.googleapis.com/compute/v1/projects/isb-cgc/zones/us-central1-a/instances/centos-6-test-2015-03-06-21-45-38].
NAME                              ZONE          MACHINE_TYPE  INTERNAL_IP   EXTERNAL_IP  STATUS
centos-6-test-2015-03-06-21-45-38 us-central1-a n1-standard-1 10.240.195.49 104.154.62.2 RUNNING
```

```
$ gcloud compute ssh centos-6-test-2015-03-06-21-45-38
Warning: Permanently added '104.154.62.2' (RSA) to the list of known hosts.
[natalie@centos-6-test-2015-03-06-21-45-38 ~]$ 

[natalie@centos-6-test-2015-03-06-21-45-38 ~]$ gcloud version
Google Cloud SDK 0.9.49

bq 2.0.18
bq-nix 2.0.18
compute 2015.02.24
core 2015.02.24
core-nix 2015.02.24
dns 2015.02.24
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.9
gsutil-nix 4.9
sql 2015.02.24


There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update


[natalie@centos-6-test-2015-03-06-21-45-38 ~]$ gsutil version -l

There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update

gsutil version: 4.9
checksum: e59dcfcdcb9040ad9abd883aee1ae47a (OK)
boto version: 2.30.0
python version: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
OS: Linux 2.6.32-504.8.1.el6.x86_64
multiprocessing available: True
using cloud sdk: True
config path: /etc/boto.cfg
gsutil path: /usr/local/share/google/google-cloud-sdk/platform/gsutil/gsutil
compiled crcmod: False
installed via package manager: False
```

```
[natalie@centos-6-test-2015-03-06-21-45-38 ~]$ sudo su
[root@centos-6-test-2015-03-06-21-45-38 natalie]# export PATH=/usr/local/bin:$PATH
[root@centos-6-test-2015-03-06-21-45-38 natalie]# gcloud version
Google Cloud SDK 0.9.49

bq 2.0.18
bq-nix 2.0.18
compute 2015.02.24
core 2015.02.24
core-nix 2015.02.24
dns 2015.02.24
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.9
gsutil-nix 4.9
sql 2015.02.24


There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update

[root@centos-6-test-2015-03-06-21-45-38 natalie]# gcloud components update

The following components will be updated:
    ----------------------------------------------------------------
    | Cloud DNS Admin Command Line Interface | 2015.03.03 | < 1 MB |
    | Cloud SDK Core Libraries               | 2015.03.03 | 1.6 MB |
    | Cloud SQL Admin Command Line Interface | 2015.03.03 | < 1 MB |
    | Compute Engine Command Line Interface  | 2015.03.03 | < 1 MB |
    ----------------------------------------------------------------

Do you want to continue (Y/n)?  Y

|- Creating update staging area                             -|
|============================================================|

|- Uninstalling: Cloud DNS Admin Command Line Interface     -|
|============================================================|
|- Uninstalling: Cloud SDK Core Libraries                   -|
|============================================================|
|- Uninstalling: Cloud SQL Admin Command Line Interface     -|
|============================================================|
|- Uninstalling: Compute Engine Command Line Interface      -|
|============================================================|
|- Installing: Cloud DNS Admin Command Line Interface       -|
|============================================================|
|- Installing: Cloud SDK Core Libraries                     -|
|============================================================|
|- Installing: Cloud SQL Admin Command Line Interface       -|
|============================================================|
|- Installing: Compute Engine Command Line Interface        -|
|============================================================|

Creating backup and activating new installation...

Update done!



[root@centos-6-test-2015-03-06-21-45-38 natalie]# gcloud version
Google Cloud SDK 0.9.50

bq 2.0.18
bq-nix 2.0.18
compute 2015.03.03
core 2015.03.03
core-nix 2015.02.24
dns 2015.03.03
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.9
gsutil-nix 4.9
sql 2015.03.03

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 290, in Shutdown
    collector.CollectCSIMetric()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 207, in CollectCSIMetric
    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))
ValueError: zero length field name in format
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 290, in Shutdown
    collector.CollectCSIMetric()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 207, in CollectCSIMetric
    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))
ValueError: zero length field name in format
[root@centos-6-test-2015-03-06-21-45-38 natalie]# 


[root@centos-6-test-2015-03-06-21-45-38 natalie]# gsutil version
gsutil version: 4.9
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", line 290, in Shutdown
    collector.CollectCSIMetric()
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", line 207, in CollectCSIMetric
    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))
ValueError: zero length field name in format
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", line 290, in Shutdown
    collector.CollectCSIMetric()
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", line 207, in CollectCSIMetric
    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))
ValueError: zero length field name in format


[root@centos-6-test-2015-03-06-21-45-38 natalie]# python --version
Python 2.6.6

```

**Comment by spacepod** [comment]
(Verifying that it wasn't due to temporarily changing the path under root:)

```
[root@centos-6-test-2015-03-06-21-45-38 natalie]# exit
[natalie@centos-6-test-2015-03-06-21-45-38 ~]$ gcloud version
Google Cloud SDK 0.9.50

bq 2.0.18
bq-nix 2.0.18
compute 2015.03.03
core 2015.03.03
core-nix 2015.02.24
dns 2015.03.03
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.9
gsutil-nix 4.9
sql 2015.03.03

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 290, in Shutdown
    collector.CollectCSIMetric()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 207, in CollectCSIMetric
    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))
ValueError: zero length field name in format
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 290, in Shutdown
    collector.CollectCSIMetric()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 207, in CollectCSIMetric
    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))
ValueError: zero length field name in format
```

**Comment by vilasj** [comment]
Thank you for reporting this issue and for the detailed logs. Apologies for the break, it is caused due to a python 2.6 incompatibility. We will fix it in our next release. Until then you can workaround the issue by replacing:

    ('{}?{}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))

with

    ('{0}?{1}'.format(_CSI_ENDPOINT, data), 'GET', None, self._user_agent))

in line 207 of /usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py

**Comment by spacepod** [comment]
You are welcome, and thank you for the patch.  When can I expect the next release?  I'm using this in the context of bdutil, and I can probably figure out how to patch the gcloud SDK before it's invoked.  But FYI any errors cause failure of the bdutil cluster deployment.  I'll see what I can do.

Also, I would strongly advise that gcloud releases are automatically tested on fresh VMs of all supported Google OSes, including Centos 6, if you're not already doing this.  https://cloud.google.com/compute/docs/operating-systems/

**Comment by vilasj** [comment]
The next release of the Cloud SDK should be out by the end of next week. Note that the Cloud SDK officially requires Python 2.7.x (https://cloud.google.com/sdk/). However, we have some efforts underway to ensure Python 2.6.x compatibility.

**Comment by spacepod** [comment]
Thanks.  Centos 6 is an officially supported GCE OS.  I haven't seen any documentation that the Cloud SDK is not compatible with all officially supported OSes, so that's good to know.  I may have just missed it, but you might want to make that documentation more visible as I image that others might be surprised that Cloud SDK isn't currently officially expected to work.

**Comment by stephenmw** [comment]
This should be fixed in the latest release. If not, please reopen.
