### ISSUE TITLE
crashes when setting project with gcloud >0.82

### ISSUE THREAD

**Issue by jeekajoo** [GoogleCloudPlatform/gcloud#39]
Hi,
with empty ~/.config/gcloud
```bash
$ gcloud init
Welcome! This command will take you through the configuration of gcloud.

Your current configuration has been set to: [default]

To continue, you must login. Would you like to login (Y/n)?  Y

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&prompt=select_account&response_type=code&client_id=xxxxxxxxxxx.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute&access_type=offline


You are now logged in as: [name@domain.tld]

Enter project id you would like to use:  myproject
Failed to run [config set project myproject]
You can use [gcloud config] to change more gcloud settings.

Your current configuration is: [default]

ERROR: gcloud crashed (AttributeError): 'module' object has no attribute 'ParsePropertyString'

If you would like to report this issue, please run the following command:
  gcloud feedback
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 197, in <module>
    main()
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 186, in main
    if properties.VALUES.core.print_unhandled_tracebacks.GetBool():
AttributeError: '_SectionCore' object has no attribute 'print_unhandled_tracebacks'
```
The problem exactly appears with 
```bash
gcloud config set project myproject
```
I downgraded to 0.9.82 to avoid this problem when setting a new project...
Once the project is set, gcloud >0.9.82 is usable..

Thanks
J.

**Comment by cherba** [comment]
It appears that [gcloud components update] has corrupted you installation.
You can try
  [gcloud components reinstall]
or simply delete and reinstall sdk by running [curl https://sdk.cloud.google.com | bash]
